### PR TITLE
add FileSystem provider

### PR DESCRIPTION
**Pull request by jramos**
This allows for secrets to be read from a local file system, e.g. those mounted via the [Kubernetes Secrets Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io).

### CODE REVIEW

**Comment by jramos** [comment]
This may actually work better as a stand-alone provider so that default search paths can be configured to make the keys less verbose. Wdyt?

**Comment by gordalina** [comment]
Thanks for contributing! I think this is a great native provider. What do you mean about the default search paths?

**Comment by jramos** [comment]
It would be something like this...

```elixir
config :hush,
  file_system_provider: [
    root_path: "/opt/thenameofyourcompany/secrets"
  ]

config :app, App,
  ssl_certificate: {:hush, FileSystem, "cert.pem"}

config :app, App.Other,
  ssl_key: {:hush, FileSystem, "private/cert.pem"}
```

That way "/opt/thenameofyourcompany/secrets" isn't needed in every key, and it would prevent arbitrary paths from being used... all the keys would need to be nested under the configured `root_path`.

The "search path" idea is similar, but you would have a list of paths, and the directories would be checked in order for the file until one was found.

```elixir
config :hush,
  file_system_provider: [
    search_paths: [
      "/opt/thenameofyourcompany/secrets",
      "/opt/secrets",
      "/etc/app"
    ]
  ]
```

**Comment by gordalina** [comment]
Added a commit, lmk what you think.

**Comment by jramos** [comment]
Looks great to me!

**Comment by gordalina** [comment]
Released in `v1.2.0` thanks!

**Pull request merged**
